name: Build
on:
  push:

jobs:
  build:
    name: Build and test
    runs-on: macos-latest

    steps:
    - name: Configure enviroment
      uses: actions/checkout@v3
    - uses: kuhnroyal/flutter-fvm-config-action@v1
    - name: Download flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
        cache-key: 'flutter-:os:-:version:'
        cache-path: '${{ runner.tool_cache }}/flutter/:os:-:version:'
    - name: Install dependencies
      run: flutter pub get
    - name: Verify formated files
      run: dart format . --set-exit-if-changed
    - name: Analyze code
      run: flutter analyze
